<?php

use Illuminate\Database\Seeder;

class CountryTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('country')->insert(['cc_fips' => 'AA','cc_iso' => 'AW','cc_tld' => '.aw','country_name' => 'Aruba',]);
        DB::table('country')->insert(['cc_fips' => 'AC','cc_iso' => 'AG','cc_tld' => '.ag','country_name' => 'Antigua and Barbuda',]);
        DB::table('country')->insert(['cc_fips' => 'AE','cc_iso' => 'AE','cc_tld' => '.ae','country_name' => 'United Arab Emirates',]);
        DB::table('country')->insert(['cc_fips' => 'AF','cc_iso' => 'AF','cc_tld' => '.af','country_name' => 'Afghanistan',]);
        DB::table('country')->insert(['cc_fips' => 'AG','cc_iso' => 'DZ','cc_tld' => '.dz','country_name' => 'Algeria',]);
        DB::table('country')->insert(['cc_fips' => 'AJ','cc_iso' => 'AZ','cc_tld' => '.az','country_name' => 'Azerbaijan',]);
        DB::table('country')->insert(['cc_fips' => 'AL','cc_iso' => 'AL','cc_tld' => '.al','country_name' => 'Albania',]);
        DB::table('country')->insert(['cc_fips' => 'AM','cc_iso' => 'AM','cc_tld' => '.am','country_name' => 'Armenia',]);
        DB::table('country')->insert(['cc_fips' => 'AN','cc_iso' => 'AD','cc_tld' => '.ad','country_name' => 'Andorra',]);
        DB::table('country')->insert(['cc_fips' => 'AO','cc_iso' => 'AO','cc_tld' => '.ao','country_name' => 'Angola',]);
        DB::table('country')->insert(['cc_fips' => 'AQ','cc_iso' => 'AS','cc_tld' => '.as','country_name' => 'American Samoa',]);
        DB::table('country')->insert(['cc_fips' => 'AR','cc_iso' => 'AR','cc_tld' => '.ar','country_name' => 'Argentina',]);
        DB::table('country')->insert(['cc_fips' => 'AS','cc_iso' => 'AU','cc_tld' => '.au','country_name' => 'Australia',]);
        DB::table('country')->insert(['cc_fips' => 'AT','cc_iso' => '-','cc_tld' => '-','country_name' => 'Ashmore and Cartier Islands',]);
        DB::table('country')->insert(['cc_fips' => 'AU','cc_iso' => 'AT','cc_tld' => '.at','country_name' => 'Austria',]);
        DB::table('country')->insert(['cc_fips' => 'AV','cc_iso' => 'AI','cc_tld' => '.ai','country_name' => 'Anguilla',]);
        DB::table('country')->insert(['cc_fips' => 'AX','cc_iso' => 'AX','cc_tld' => '.ax','country_name' => 'Åland Islands',]);
        DB::table('country')->insert(['cc_fips' => 'AY','cc_iso' => 'AQ','cc_tld' => '.aq','country_name' => 'Antarctica',]);
        DB::table('country')->insert(['cc_fips' => 'BA','cc_iso' => 'BH','cc_tld' => '.bh','country_name' => 'Bahrain',]);
        DB::table('country')->insert(['cc_fips' => 'BB','cc_iso' => 'BB','cc_tld' => '.bb','country_name' => 'Barbados',]);
        DB::table('country')->insert(['cc_fips' => 'BC','cc_iso' => 'BW','cc_tld' => '.bw','country_name' => 'Botswana',]);
        DB::table('country')->insert(['cc_fips' => 'BD','cc_iso' => 'BM','cc_tld' => '.bm','country_name' => 'Bermuda',]);
        DB::table('country')->insert(['cc_fips' => 'BE','cc_iso' => 'BE','cc_tld' => '.be','country_name' => 'Belgium',]);
        DB::table('country')->insert(['cc_fips' => 'BF','cc_iso' => 'BS','cc_tld' => '.bs','country_name' => 'Bahamas, The',]);
        DB::table('country')->insert(['cc_fips' => 'BG','cc_iso' => 'BD','cc_tld' => '.bd','country_name' => 'Bangladesh',]);
        DB::table('country')->insert(['cc_fips' => 'BH','cc_iso' => 'BZ','cc_tld' => '.bz','country_name' => 'Belize',]);
        DB::table('country')->insert(['cc_fips' => 'BK','cc_iso' => 'BA','cc_tld' => '.ba','country_name' => 'Bosnia and Herzegovina',]);
        DB::table('country')->insert(['cc_fips' => 'BL','cc_iso' => 'BO','cc_tld' => '.bo','country_name' => 'Bolivia',]);
        DB::table('country')->insert(['cc_fips' => 'BM','cc_iso' => 'MM','cc_tld' => '.mm','country_name' => 'Myanmar',]);
        DB::table('country')->insert(['cc_fips' => 'BN','cc_iso' => 'BJ','cc_tld' => '.bj','country_name' => 'Benin',]);
        DB::table('country')->insert(['cc_fips' => 'BO','cc_iso' => 'BY','cc_tld' => '.by','country_name' => 'Belarus',]);
        DB::table('country')->insert(['cc_fips' => 'BP','cc_iso' => 'SB','cc_tld' => '.sb','country_name' => 'Solomon Islands',]);
        DB::table('country')->insert(['cc_fips' => 'BQ','cc_iso' => '-','cc_tld' => '-','country_name' => 'Navassa Island',]);
        DB::table('country')->insert(['cc_fips' => 'BR','cc_iso' => 'BR','cc_tld' => '.br','country_name' => 'Brazil',]);
        DB::table('country')->insert(['cc_fips' => 'BS','cc_iso' => '-','cc_tld' => '-','country_name' => 'Bassas da India',]);
        DB::table('country')->insert(['cc_fips' => 'BT','cc_iso' => 'BT','cc_tld' => '.bt','country_name' => 'Bhutan',]);
        DB::table('country')->insert(['cc_fips' => 'BU','cc_iso' => 'BG','cc_tld' => '.bg','country_name' => 'Bulgaria',]);
        DB::table('country')->insert(['cc_fips' => 'BV','cc_iso' => 'BV','cc_tld' => '.bv','country_name' => 'Bouvet Island',]);
        DB::table('country')->insert(['cc_fips' => 'BX','cc_iso' => 'BN','cc_tld' => '.bn','country_name' => 'Brunei',]);
        DB::table('country')->insert(['cc_fips' => 'BY','cc_iso' => 'BI','cc_tld' => '.bi','country_name' => 'Burundi',]);
        DB::table('country')->insert(['cc_fips' => 'CA','cc_iso' => 'CA','cc_tld' => '.ca','country_name' => 'Canada',]);
        DB::table('country')->insert(['cc_fips' => 'CB','cc_iso' => 'KH','cc_tld' => '.kh','country_name' => 'Cambodia',]);
        DB::table('country')->insert(['cc_fips' => 'CD','cc_iso' => 'TD','cc_tld' => '.td','country_name' => 'Chad',]);
        DB::table('country')->insert(['cc_fips' => 'CE','cc_iso' => 'LK','cc_tld' => '.lk','country_name' => 'Sri Lanka',]);
        DB::table('country')->insert(['cc_fips' => 'CF','cc_iso' => 'CG','cc_tld' => '.cg','country_name' => 'Congo, Republic of the',]);
        DB::table('country')->insert(['cc_fips' => 'CG','cc_iso' => 'CD','cc_tld' => '.cd','country_name' => 'Congo, Democratic Republic of the',]);
        DB::table('country')->insert(['cc_fips' => 'CH','cc_iso' => 'CN','cc_tld' => '.cn','country_name' => 'China',]);
        DB::table('country')->insert(['cc_fips' => 'CI','cc_iso' => 'CL','cc_tld' => '.cl','country_name' => 'Chile',]);
        DB::table('country')->insert(['cc_fips' => 'CJ','cc_iso' => 'KY','cc_tld' => '.ky','country_name' => 'Cayman Islands',]);
        DB::table('country')->insert(['cc_fips' => 'CK','cc_iso' => 'CC','cc_tld' => '.cc','country_name' => 'Cocos (Keeling) Islands',]);
        DB::table('country')->insert(['cc_fips' => 'CM','cc_iso' => 'CM','cc_tld' => '.cm','country_name' => 'Cameroon',]);
        DB::table('country')->insert(['cc_fips' => 'CN','cc_iso' => 'KM','cc_tld' => '.km','country_name' => 'Comoros',]);
        DB::table('country')->insert(['cc_fips' => 'CO','cc_iso' => 'CO','cc_tld' => '.co','country_name' => 'Colombia',]);
        DB::table('country')->insert(['cc_fips' => 'CQ','cc_iso' => 'MP','cc_tld' => '.mp','country_name' => 'Northern Mariana Islands',]);
        DB::table('country')->insert(['cc_fips' => 'CR','cc_iso' => '-','cc_tld' => '-','country_name' => 'Coral Sea Islands',]);
        DB::table('country')->insert(['cc_fips' => 'CS','cc_iso' => 'CR','cc_tld' => '.cr','country_name' => 'Costa Rica',]);
        DB::table('country')->insert(['cc_fips' => 'CT','cc_iso' => 'CF','cc_tld' => '.cf','country_name' => 'Central African Republic',]);
        DB::table('country')->insert(['cc_fips' => 'CU','cc_iso' => 'CU','cc_tld' => '.cu','country_name' => 'Cuba',]);
        DB::table('country')->insert(['cc_fips' => 'CV','cc_iso' => 'CV','cc_tld' => '.cv','country_name' => 'Cape Verde',]);
        DB::table('country')->insert(['cc_fips' => 'CW','cc_iso' => 'CK','cc_tld' => '.ck','country_name' => 'Cook Islands',]);
        DB::table('country')->insert(['cc_fips' => 'CY','cc_iso' => 'CY','cc_tld' => '.cy','country_name' => 'Cyprus',]);
        DB::table('country')->insert(['cc_fips' => 'DA','cc_iso' => 'DK','cc_tld' => '.dk','country_name' => 'Denmark',]);
        DB::table('country')->insert(['cc_fips' => 'DJ','cc_iso' => 'DJ','cc_tld' => '.dj','country_name' => 'Djibouti',]);
        DB::table('country')->insert(['cc_fips' => 'DO','cc_iso' => 'DM','cc_tld' => '.dm','country_name' => 'Dominica',]);
        DB::table('country')->insert(['cc_fips' => 'DQ','cc_iso' => 'UM','cc_tld' => '-','country_name' => 'Jarvis Island',]);
        DB::table('country')->insert(['cc_fips' => 'DR','cc_iso' => 'DO','cc_tld' => '.do','country_name' => 'Dominican Republic',]);
        DB::table('country')->insert(['cc_fips' => 'DX','cc_iso' => '-','cc_tld' => '-','country_name' => 'Dhekelia Sovereign Base Area',]);
        DB::table('country')->insert(['cc_fips' => 'EC','cc_iso' => 'EC','cc_tld' => '.ec','country_name' => 'Ecuador',]);
        DB::table('country')->insert(['cc_fips' => 'EG','cc_iso' => 'EG','cc_tld' => '.eg','country_name' => 'Egypt',]);
        DB::table('country')->insert(['cc_fips' => 'EI','cc_iso' => 'IE','cc_tld' => '.ie','country_name' => 'Ireland',]);
        DB::table('country')->insert(['cc_fips' => 'EK','cc_iso' => 'GQ','cc_tld' => '.gq','country_name' => 'Equatorial Guinea',]);
        DB::table('country')->insert(['cc_fips' => 'EN','cc_iso' => 'EE','cc_tld' => '.ee','country_name' => 'Estonia',]);
        DB::table('country')->insert(['cc_fips' => 'ER','cc_iso' => 'ER','cc_tld' => '.er','country_name' => 'Eritrea',]);
        DB::table('country')->insert(['cc_fips' => 'ES','cc_iso' => 'SV','cc_tld' => '.sv','country_name' => 'El Salvador',]);
        DB::table('country')->insert(['cc_fips' => 'ET','cc_iso' => 'ET','cc_tld' => '.et','country_name' => 'Ethiopia',]);
        DB::table('country')->insert(['cc_fips' => 'EU','cc_iso' => '-','cc_tld' => '-','country_name' => 'Europa Island',]);
        DB::table('country')->insert(['cc_fips' => 'EZ','cc_iso' => 'CZ','cc_tld' => '.cz','country_name' => 'Czech Republic',]);
        DB::table('country')->insert(['cc_fips' => 'FG','cc_iso' => 'GF','cc_tld' => '.gf','country_name' => 'French Guiana',]);
        DB::table('country')->insert(['cc_fips' => 'FI','cc_iso' => 'FI','cc_tld' => '.fi','country_name' => 'Finland',]);
        DB::table('country')->insert(['cc_fips' => 'FJ','cc_iso' => 'FJ','cc_tld' => '.fj','country_name' => 'Fiji',]);
        DB::table('country')->insert(['cc_fips' => 'FK','cc_iso' => 'FK','cc_tld' => '.fk','country_name' => 'Falkland Islands (Islas Malvinas)',]);
        DB::table('country')->insert(['cc_fips' => 'FM','cc_iso' => 'FM','cc_tld' => '.fm','country_name' => 'Micronesia, Federated States of',]);
        DB::table('country')->insert(['cc_fips' => 'FO','cc_iso' => 'FO','cc_tld' => '.fo','country_name' => 'Faroe Islands',]);
        DB::table('country')->insert(['cc_fips' => 'FP','cc_iso' => 'PF','cc_tld' => '.pf','country_name' => 'French Polynesia',]);
        DB::table('country')->insert(['cc_fips' => 'FQ','cc_iso' => 'UM','cc_tld' => '-','country_name' => 'Baker Island',]);
        DB::table('country')->insert(['cc_fips' => 'FR','cc_iso' => 'FR','cc_tld' => '.fr','country_name' => 'France',]);
        DB::table('country')->insert(['cc_fips' => 'FS','cc_iso' => 'TF','cc_tld' => '.tf','country_name' => 'French Southern and Antarctic Lands',]);
        DB::table('country')->insert(['cc_fips' => 'GA','cc_iso' => 'GM','cc_tld' => '.gm','country_name' => 'Gambia, The',]);
        DB::table('country')->insert(['cc_fips' => 'GB','cc_iso' => 'GA','cc_tld' => '.ga','country_name' => 'Gabon',]);
        DB::table('country')->insert(['cc_fips' => 'GG','cc_iso' => 'GE','cc_tld' => '.ge','country_name' => 'Georgia',]);
        DB::table('country')->insert(['cc_fips' => 'GH','cc_iso' => 'GH','cc_tld' => '.gh','country_name' => 'Ghana',]);
        DB::table('country')->insert(['cc_fips' => 'GI','cc_iso' => 'GI','cc_tld' => '.gi','country_name' => 'Gibraltar',]);
        DB::table('country')->insert(['cc_fips' => 'GJ','cc_iso' => 'GD','cc_tld' => '.gd','country_name' => 'Grenada',]);
        DB::table('country')->insert(['cc_fips' => 'GK','cc_iso' => '-','cc_tld' => '.gg','country_name' => 'Guernsey',]);
        DB::table('country')->insert(['cc_fips' => 'GL','cc_iso' => 'GL','cc_tld' => '.gl','country_name' => 'Greenland',]);
        DB::table('country')->insert(['cc_fips' => 'GM','cc_iso' => 'DE','cc_tld' => '.de','country_name' => 'Germany',]);
        DB::table('country')->insert(['cc_fips' => 'GO','cc_iso' => '-','cc_tld' => '-','country_name' => 'Glorioso Islands',]);
        DB::table('country')->insert(['cc_fips' => 'GP','cc_iso' => 'GP','cc_tld' => '.gp','country_name' => 'Guadeloupe',]);
        DB::table('country')->insert(['cc_fips' => 'GQ','cc_iso' => 'GU','cc_tld' => '.gu','country_name' => 'Guam',]);
        DB::table('country')->insert(['cc_fips' => 'GR','cc_iso' => 'GR','cc_tld' => '.gr','country_name' => 'Greece',]);
        DB::table('country')->insert(['cc_fips' => 'GT','cc_iso' => 'GT','cc_tld' => '.gt','country_name' => 'Guatemala',]);
        DB::table('country')->insert(['cc_fips' => 'GV','cc_iso' => 'GN','cc_tld' => '.gn','country_name' => 'Guinea',]);
        DB::table('country')->insert(['cc_fips' => 'GY','cc_iso' => 'GY','cc_tld' => '.gy','country_name' => 'Guyana',]);
        DB::table('country')->insert(['cc_fips' => 'GZ','cc_iso' => '-','cc_tld' => '-','country_name' => 'Gaza Strip',]);
        DB::table('country')->insert(['cc_fips' => 'HA','cc_iso' => 'HT','cc_tld' => '.ht','country_name' => 'Haiti',]);
        DB::table('country')->insert(['cc_fips' => 'HK','cc_iso' => 'HK','cc_tld' => '.hk','country_name' => 'Hong Kong',]);
        DB::table('country')->insert(['cc_fips' => 'HM','cc_iso' => 'HM','cc_tld' => '.hm','country_name' => 'Heard Island and McDonald Islands',]);
        DB::table('country')->insert(['cc_fips' => 'HO','cc_iso' => 'HN','cc_tld' => '.hn','country_name' => 'Honduras',]);
        DB::table('country')->insert(['cc_fips' => 'HQ','cc_iso' => 'UM','cc_tld' => '-','country_name' => 'Howland Island',]);
        DB::table('country')->insert(['cc_fips' => 'HR','cc_iso' => 'HR','cc_tld' => '.hr','country_name' => 'Croatia',]);
        DB::table('country')->insert(['cc_fips' => 'HU','cc_iso' => 'HU','cc_tld' => '.hu','country_name' => 'Hungary',]);
        DB::table('country')->insert(['cc_fips' => 'IC','cc_iso' => 'IS','cc_tld' => '.is','country_name' => 'Iceland',]);
        DB::table('country')->insert(['cc_fips' => 'ID','cc_iso' => 'ID','cc_tld' => '.id','country_name' => 'Indonesia',]);
        DB::table('country')->insert(['cc_fips' => 'IM','cc_iso' => 'IM','cc_tld' => '.im','country_name' => 'Isle of Man',]);
        DB::table('country')->insert(['cc_fips' => 'IN','cc_iso' => 'IN','cc_tld' => '.in','country_name' => 'India',]);
        DB::table('country')->insert(['cc_fips' => 'IO','cc_iso' => 'IO','cc_tld' => '.io','country_name' => 'British Indian Ocean Territory',]);
        DB::table('country')->insert(['cc_fips' => 'IP','cc_iso' => '-','cc_tld' => '-','country_name' => 'Clipperton Island',]);
        DB::table('country')->insert(['cc_fips' => 'IR','cc_iso' => 'IR','cc_tld' => '.ir','country_name' => 'Iran',]);
        DB::table('country')->insert(['cc_fips' => 'IS','cc_iso' => 'IL','cc_tld' => '.il','country_name' => 'Israel',]);
        DB::table('country')->insert(['cc_fips' => 'IT','cc_iso' => 'IT','cc_tld' => '.it','country_name' => 'Italy',]);
        DB::table('country')->insert(['cc_fips' => 'IV','cc_iso' => 'CI','cc_tld' => '.ci','country_name' => 'Cote d\'Ivoire',]);
        DB::table('country')->insert(['cc_fips' => 'IZ','cc_iso' => 'IQ','cc_tld' => '.iq','country_name' => 'Iraq',]);
        DB::table('country')->insert(['cc_fips' => 'JA','cc_iso' => 'JP','cc_tld' => '.jp','country_name' => 'Japan',]);
        DB::table('country')->insert(['cc_fips' => 'JE','cc_iso' => 'JE','cc_tld' => '.je','country_name' => 'Jersey',]);
        DB::table('country')->insert(['cc_fips' => 'JM','cc_iso' => 'JM','cc_tld' => '.jm','country_name' => 'Jamaica',]);
        DB::table('country')->insert(['cc_fips' => 'JN','cc_iso' => 'SJ','cc_tld' => '-','country_name' => 'Jan Mayen',]);
        DB::table('country')->insert(['cc_fips' => 'JO','cc_iso' => 'JO','cc_tld' => '.jo','country_name' => 'Jordan',]);
        DB::table('country')->insert(['cc_fips' => 'JQ','cc_iso' => 'UM','cc_tld' => '-','country_name' => 'Johnston Atoll',]);
        DB::table('country')->insert(['cc_fips' => 'JU','cc_iso' => '-','cc_tld' => '-','country_name' => 'Juan de Nova Island',]);
        DB::table('country')->insert(['cc_fips' => 'KE','cc_iso' => 'KE','cc_tld' => '.ke','country_name' => 'Kenya',]);
        DB::table('country')->insert(['cc_fips' => 'KG','cc_iso' => 'KG','cc_tld' => '.kg','country_name' => 'Kyrgyzstan',]);
        DB::table('country')->insert(['cc_fips' => 'KN','cc_iso' => 'KP','cc_tld' => '.kp','country_name' => 'Korea, North',]);
        DB::table('country')->insert(['cc_fips' => 'KQ','cc_iso' => 'UM','cc_tld' => '-','country_name' => 'Kingman Reef',]);
        DB::table('country')->insert(['cc_fips' => 'KR','cc_iso' => 'KI','cc_tld' => '.ki','country_name' => 'Kiribati',]);
        DB::table('country')->insert(['cc_fips' => 'KS','cc_iso' => 'KR','cc_tld' => '.kr','country_name' => 'Korea, South',]);
        DB::table('country')->insert(['cc_fips' => 'KT','cc_iso' => 'CX','cc_tld' => '.cx','country_name' => 'Christmas Island',]);
        DB::table('country')->insert(['cc_fips' => 'KU','cc_iso' => 'KW','cc_tld' => '.kw','country_name' => 'Kuwait',]);
        DB::table('country')->insert(['cc_fips' => 'KV','cc_iso' => 'KV','cc_tld' => '-','country_name' => 'Kosovo',]);
        DB::table('country')->insert(['cc_fips' => 'KZ','cc_iso' => 'KZ','cc_tld' => '.kz','country_name' => 'Kazakhstan',]);
        DB::table('country')->insert(['cc_fips' => 'LA','cc_iso' => 'LA','cc_tld' => '.la','country_name' => 'Laos',]);
        DB::table('country')->insert(['cc_fips' => 'LE','cc_iso' => 'LB','cc_tld' => '.lb','country_name' => 'Lebanon',]);
        DB::table('country')->insert(['cc_fips' => 'LG','cc_iso' => 'LV','cc_tld' => '.lv','country_name' => 'Latvia',]);
        DB::table('country')->insert(['cc_fips' => 'LH','cc_iso' => 'LT','cc_tld' => '.lt','country_name' => 'Lithuania',]);
        DB::table('country')->insert(['cc_fips' => 'LI','cc_iso' => 'LR','cc_tld' => '.lr','country_name' => 'Liberia',]);
        DB::table('country')->insert(['cc_fips' => 'LO','cc_iso' => 'SK','cc_tld' => '.sk','country_name' => 'Slovakia',]);
        DB::table('country')->insert(['cc_fips' => 'LQ','cc_iso' => 'UM','cc_tld' => '-','country_name' => 'Palmyra Atoll',]);
        DB::table('country')->insert(['cc_fips' => 'LS','cc_iso' => 'LI','cc_tld' => '.li','country_name' => 'Liechtenstein',]);
        DB::table('country')->insert(['cc_fips' => 'LT','cc_iso' => 'LS','cc_tld' => '.ls','country_name' => 'Lesotho',]);
        DB::table('country')->insert(['cc_fips' => 'LU','cc_iso' => 'LU','cc_tld' => '.lu','country_name' => 'Luxembourg',]);
        DB::table('country')->insert(['cc_fips' => 'LY','cc_iso' => 'LY','cc_tld' => '.ly','country_name' => 'Libyan Arab',]);
        DB::table('country')->insert(['cc_fips' => 'MA','cc_iso' => 'MG','cc_tld' => '.mg','country_name' => 'Madagascar',]);
        DB::table('country')->insert(['cc_fips' => 'MB','cc_iso' => 'MQ','cc_tld' => '.mq','country_name' => 'Martinique',]);
        DB::table('country')->insert(['cc_fips' => 'MC','cc_iso' => 'MO','cc_tld' => '.mo','country_name' => 'Macau',]);
        DB::table('country')->insert(['cc_fips' => 'MD','cc_iso' => 'MD','cc_tld' => '.md','country_name' => 'Moldova, Republic of',]);
        DB::table('country')->insert(['cc_fips' => 'MF','cc_iso' => 'YT','cc_tld' => '.yt','country_name' => 'Mayotte',]);
        DB::table('country')->insert(['cc_fips' => 'MG','cc_iso' => 'MN','cc_tld' => '.mn','country_name' => 'Mongolia',]);
        DB::table('country')->insert(['cc_fips' => 'MH','cc_iso' => 'MS','cc_tld' => '.ms','country_name' => 'Montserrat',]);
        DB::table('country')->insert(['cc_fips' => 'MI','cc_iso' => 'MW','cc_tld' => '.mw','country_name' => 'Malawi',]);
        DB::table('country')->insert(['cc_fips' => 'MJ','cc_iso' => 'ME','cc_tld' => '.me','country_name' => 'Montenegro',]);
        DB::table('country')->insert(['cc_fips' => 'MK','cc_iso' => 'MK','cc_tld' => '.mk','country_name' => 'The Former Yugoslav Republic of Macedonia',]);
        DB::table('country')->insert(['cc_fips' => 'ML','cc_iso' => 'ML','cc_tld' => '.ml','country_name' => 'Mali',]);
        DB::table('country')->insert(['cc_fips' => 'MN','cc_iso' => 'MC','cc_tld' => '.mc','country_name' => 'Monaco',]);
        DB::table('country')->insert(['cc_fips' => 'MO','cc_iso' => 'MA','cc_tld' => '.ma','country_name' => 'Morocco',]);
        DB::table('country')->insert(['cc_fips' => 'MP','cc_iso' => 'MU','cc_tld' => '.mu','country_name' => 'Mauritius',]);
        DB::table('country')->insert(['cc_fips' => 'MQ','cc_iso' => 'UM','cc_tld' => '-','country_name' => 'Midway Islands',]);
        DB::table('country')->insert(['cc_fips' => 'MR','cc_iso' => 'MR','cc_tld' => '.mr','country_name' => 'Mauritania',]);
        DB::table('country')->insert(['cc_fips' => 'MT','cc_iso' => 'MT','cc_tld' => '.mt','country_name' => 'Malta',]);
        DB::table('country')->insert(['cc_fips' => 'MU','cc_iso' => 'OM','cc_tld' => '.om','country_name' => 'Oman',]);
        DB::table('country')->insert(['cc_fips' => 'MV','cc_iso' => 'MV','cc_tld' => '.mv','country_name' => 'Maldives',]);
        DB::table('country')->insert(['cc_fips' => 'MX','cc_iso' => 'MX','cc_tld' => '.mx','country_name' => 'Mexico',]);
        DB::table('country')->insert(['cc_fips' => 'MY','cc_iso' => 'MY','cc_tld' => '.my','country_name' => 'Malaysia',]);
        DB::table('country')->insert(['cc_fips' => 'MZ','cc_iso' => 'MZ','cc_tld' => '.mz','country_name' => 'Mozambique',]);
        DB::table('country')->insert(['cc_fips' => 'NC','cc_iso' => 'NC','cc_tld' => '.nc','country_name' => 'New Caledonia',]);
        DB::table('country')->insert(['cc_fips' => 'NE','cc_iso' => 'NU','cc_tld' => '.nu','country_name' => 'Niue',]);
        DB::table('country')->insert(['cc_fips' => 'NF','cc_iso' => 'NF','cc_tld' => '.nf','country_name' => 'Norfolk Island',]);
        DB::table('country')->insert(['cc_fips' => 'NG','cc_iso' => 'NE','cc_tld' => '.ne','country_name' => 'Niger',]);
        DB::table('country')->insert(['cc_fips' => 'NH','cc_iso' => 'VU','cc_tld' => '.vu','country_name' => 'Vanuatu',]);
        DB::table('country')->insert(['cc_fips' => 'NI','cc_iso' => 'NG','cc_tld' => '.ng','country_name' => 'Nigeria',]);
        DB::table('country')->insert(['cc_fips' => 'NL','cc_iso' => 'NL','cc_tld' => '.nl','country_name' => 'Netherlands',]);
        DB::table('country')->insert(['cc_fips' => 'NM','cc_iso' => '','cc_tld' => '','country_name' => 'No Man\'s Land',]);
        DB::table('country')->insert(['cc_fips' => 'NO','cc_iso' => 'NO','cc_tld' => '.no','country_name' => 'Norway',]);
        DB::table('country')->insert(['cc_fips' => 'NP','cc_iso' => 'NP','cc_tld' => '.np','country_name' => 'Nepal',]);
        DB::table('country')->insert(['cc_fips' => 'NR','cc_iso' => 'NR','cc_tld' => '.nr','country_name' => 'Nauru',]);
        DB::table('country')->insert(['cc_fips' => 'NS','cc_iso' => 'SR','cc_tld' => '.sr','country_name' => 'Suriname',]);
        DB::table('country')->insert(['cc_fips' => 'NT','cc_iso' => 'AN','cc_tld' => '.an','country_name' => 'Netherlands Antilles',]);
        DB::table('country')->insert(['cc_fips' => 'NU','cc_iso' => 'NI','cc_tld' => '.ni','country_name' => 'Nicaragua',]);
        DB::table('country')->insert(['cc_fips' => 'NZ','cc_iso' => 'NZ','cc_tld' => '.nz','country_name' => 'New Zealand',]);
        DB::table('country')->insert(['cc_fips' => 'PA','cc_iso' => 'PY','cc_tld' => '.py','country_name' => 'Paraguay',]);
        DB::table('country')->insert(['cc_fips' => 'PC','cc_iso' => 'PN','cc_tld' => '.pn','country_name' => 'Pitcairn Islands',]);
        DB::table('country')->insert(['cc_fips' => 'PE','cc_iso' => 'PE','cc_tld' => '.pe','country_name' => 'Peru',]);
        DB::table('country')->insert(['cc_fips' => 'PF','cc_iso' => '-','cc_tld' => '-','country_name' => 'Paracel Islands',]);
        DB::table('country')->insert(['cc_fips' => 'PG','cc_iso' => '-','cc_tld' => '-','country_name' => 'Spratly Islands',]);
        DB::table('country')->insert(['cc_fips' => 'PK','cc_iso' => 'PK','cc_tld' => '.pk','country_name' => 'Pakistan',]);
        DB::table('country')->insert(['cc_fips' => 'PL','cc_iso' => 'PL','cc_tld' => '.pl','country_name' => 'Poland',]);
        DB::table('country')->insert(['cc_fips' => 'PM','cc_iso' => 'PA','cc_tld' => '.pa','country_name' => 'Panama',]);
        DB::table('country')->insert(['cc_fips' => 'PO','cc_iso' => 'PT','cc_tld' => '.pt','country_name' => 'Portugal',]);
        DB::table('country')->insert(['cc_fips' => 'PP','cc_iso' => 'PG','cc_tld' => '.pg','country_name' => 'Papua New Guinea',]);
        DB::table('country')->insert(['cc_fips' => 'PS','cc_iso' => 'PW','cc_tld' => '.pw','country_name' => 'Palau',]);
        DB::table('country')->insert(['cc_fips' => 'PU','cc_iso' => 'GW','cc_tld' => '.gw','country_name' => 'Guinea-Bissau',]);
        DB::table('country')->insert(['cc_fips' => 'QA','cc_iso' => 'QA','cc_tld' => '.qa','country_name' => 'Qatar',]);
        DB::table('country')->insert(['cc_fips' => 'RE','cc_iso' => 'RE','cc_tld' => '.re','country_name' => 'Reunion',]);
        DB::table('country')->insert(['cc_fips' => 'RI','cc_iso' => 'RS','cc_tld' => '.rs','country_name' => 'Serbia',]);
        DB::table('country')->insert(['cc_fips' => 'RM','cc_iso' => 'MH','cc_tld' => '.mh','country_name' => 'Marshall Islands',]);
        DB::table('country')->insert(['cc_fips' => 'RN','cc_iso' => 'MF','cc_tld' => '-','country_name' => 'Saint Martin',]);
        DB::table('country')->insert(['cc_fips' => 'RO','cc_iso' => 'RO','cc_tld' => '.ro','country_name' => 'Romania',]);
        DB::table('country')->insert(['cc_fips' => 'RP','cc_iso' => 'PH','cc_tld' => '.ph','country_name' => 'Philippines',]);
        DB::table('country')->insert(['cc_fips' => 'RQ','cc_iso' => 'PR','cc_tld' => '.pr','country_name' => 'Puerto Rico',]);
        DB::table('country')->insert(['cc_fips' => 'RS','cc_iso' => 'RU','cc_tld' => '.ru','country_name' => 'Russia',]);
        DB::table('country')->insert(['cc_fips' => 'RW','cc_iso' => 'RW','cc_tld' => '.rw','country_name' => 'Rwanda',]);
        DB::table('country')->insert(['cc_fips' => 'SA','cc_iso' => 'SA','cc_tld' => '.sa','country_name' => 'Saudi Arabia',]);
        DB::table('country')->insert(['cc_fips' => 'SB','cc_iso' => 'PM','cc_tld' => '.pm','country_name' => 'Saint Pierre and Miquelon',]);
        DB::table('country')->insert(['cc_fips' => 'SC','cc_iso' => 'KN','cc_tld' => '.kn','country_name' => 'Saint Kitts and Nevis',]);
        DB::table('country')->insert(['cc_fips' => 'SE','cc_iso' => 'SC','cc_tld' => '.sc','country_name' => 'Seychelles',]);
        DB::table('country')->insert(['cc_fips' => 'SF','cc_iso' => 'ZA','cc_tld' => '.za','country_name' => 'South Africa',]);
        DB::table('country')->insert(['cc_fips' => 'SG','cc_iso' => 'SN','cc_tld' => '.sn','country_name' => 'Senegal',]);
        DB::table('country')->insert(['cc_fips' => 'SH','cc_iso' => 'SH','cc_tld' => '.sh','country_name' => 'Saint Helena',]);
        DB::table('country')->insert(['cc_fips' => 'SI','cc_iso' => 'SI','cc_tld' => '.si','country_name' => 'Slovenia',]);
        DB::table('country')->insert(['cc_fips' => 'SL','cc_iso' => 'SL','cc_tld' => '.sl','country_name' => 'Sierra Leone',]);
        DB::table('country')->insert(['cc_fips' => 'SM','cc_iso' => 'SM','cc_tld' => '.sm','country_name' => 'San Marino',]);
        DB::table('country')->insert(['cc_fips' => 'SN','cc_iso' => 'SG','cc_tld' => '.sg','country_name' => 'Singapore',]);
        DB::table('country')->insert(['cc_fips' => 'SO','cc_iso' => 'SO','cc_tld' => '.so','country_name' => 'Somalia',]);
        DB::table('country')->insert(['cc_fips' => 'SP','cc_iso' => 'ES','cc_tld' => '.es','country_name' => 'Spain',]);
        DB::table('country')->insert(['cc_fips' => 'ST','cc_iso' => 'LC','cc_tld' => '.lc','country_name' => 'Saint Lucia',]);
        DB::table('country')->insert(['cc_fips' => 'SU','cc_iso' => 'SD','cc_tld' => '.sd','country_name' => 'Sudan',]);
        DB::table('country')->insert(['cc_fips' => 'SV','cc_iso' => 'SJ','cc_tld' => '.sj','country_name' => 'Svalbard',]);
        DB::table('country')->insert(['cc_fips' => 'SW','cc_iso' => 'SE','cc_tld' => '.se','country_name' => 'Sweden',]);
        DB::table('country')->insert(['cc_fips' => 'SX','cc_iso' => 'GS','cc_tld' => '.gs','country_name' => 'South Georgia and the Islands',]);
        DB::table('country')->insert(['cc_fips' => 'SY','cc_iso' => 'SY','cc_tld' => '.sy','country_name' => 'Syrian Arab Republic',]);
        DB::table('country')->insert(['cc_fips' => 'SZ','cc_iso' => 'CH','cc_tld' => '.ch','country_name' => 'Switzerland',]);
        DB::table('country')->insert(['cc_fips' => 'TD','cc_iso' => 'TT','cc_tld' => '.tt','country_name' => 'Trinidad and Tobago',]);
        DB::table('country')->insert(['cc_fips' => 'TE','cc_iso' => '-','cc_tld' => '-','country_name' => 'Tromelin Island',]);
        DB::table('country')->insert(['cc_fips' => 'TH','cc_iso' => 'TH','cc_tld' => '.th','country_name' => 'Thailand',]);
        DB::table('country')->insert(['cc_fips' => 'TI','cc_iso' => 'TJ','cc_tld' => '.tj','country_name' => 'Tajikistan',]);
        DB::table('country')->insert(['cc_fips' => 'TK','cc_iso' => 'TC','cc_tld' => '.tc','country_name' => 'Turks and Caicos Islands',]);
        DB::table('country')->insert(['cc_fips' => 'TL','cc_iso' => 'TK','cc_tld' => '.tk','country_name' => 'Tokelau',]);
        DB::table('country')->insert(['cc_fips' => 'TN','cc_iso' => 'TO','cc_tld' => '.to','country_name' => 'Tonga',]);
        DB::table('country')->insert(['cc_fips' => 'TO','cc_iso' => 'TG','cc_tld' => '.tg','country_name' => 'Togo',]);
        DB::table('country')->insert(['cc_fips' => 'TP','cc_iso' => 'ST','cc_tld' => '.st','country_name' => 'Sao Tome and Principe',]);
        DB::table('country')->insert(['cc_fips' => 'TS','cc_iso' => 'TN','cc_tld' => '.tn','country_name' => 'Tunisia',]);
        DB::table('country')->insert(['cc_fips' => 'TT','cc_iso' => 'TL','cc_tld' => '.tl','country_name' => 'East Timor',]);
        DB::table('country')->insert(['cc_fips' => 'TU','cc_iso' => 'TR','cc_tld' => '.tr','country_name' => 'Turkey',]);
        DB::table('country')->insert(['cc_fips' => 'TV','cc_iso' => 'TV','cc_tld' => '.tv','country_name' => 'Tuvalu',]);
        DB::table('country')->insert(['cc_fips' => 'TW','cc_iso' => 'TW','cc_tld' => '.tw','country_name' => 'Taiwan',]);
        DB::table('country')->insert(['cc_fips' => 'TX','cc_iso' => 'TM','cc_tld' => '.tm','country_name' => 'Turkmenistan',]);
        DB::table('country')->insert(['cc_fips' => 'TZ','cc_iso' => 'TZ','cc_tld' => '.tz','country_name' => 'Tanzania, United Republic of',]);
        DB::table('country')->insert(['cc_fips' => 'UG','cc_iso' => 'UG','cc_tld' => '.ug','country_name' => 'Uganda',]);
        DB::table('country')->insert(['cc_fips' => 'UK','cc_iso' => 'GB','cc_tld' => '.uk','country_name' => 'United Kingdom',]);
        DB::table('country')->insert(['cc_fips' => 'UP','cc_iso' => 'UA','cc_tld' => '.ua','country_name' => 'Ukraine',]);
        DB::table('country')->insert(['cc_fips' => 'US','cc_iso' => 'US','cc_tld' => '.us','country_name' => 'United States',]);
        DB::table('country')->insert(['cc_fips' => 'UV','cc_iso' => 'BF','cc_tld' => '.bf','country_name' => 'Burkina Faso',]);
        DB::table('country')->insert(['cc_fips' => 'UY','cc_iso' => 'UY','cc_tld' => '.uy','country_name' => 'Uruguay',]);
        DB::table('country')->insert(['cc_fips' => 'UZ','cc_iso' => 'UZ','cc_tld' => '.uz','country_name' => 'Uzbekistan',]);
        DB::table('country')->insert(['cc_fips' => 'VC','cc_iso' => 'VC','cc_tld' => '.vc','country_name' => 'Saint Vincent and the Grenadines',]);
        DB::table('country')->insert(['cc_fips' => 'VE','cc_iso' => 'VE','cc_tld' => '.ve','country_name' => 'Venezuela',]);
        DB::table('country')->insert(['cc_fips' => 'VI','cc_iso' => 'VG','cc_tld' => '.vg','country_name' => 'British Virgin Islands',]);
        DB::table('country')->insert(['cc_fips' => 'VM','cc_iso' => 'VN','cc_tld' => '.vn','country_name' => 'Vietnam',]);
        DB::table('country')->insert(['cc_fips' => 'VQ','cc_iso' => 'VI','cc_tld' => '.vi','country_name' => 'Virgin Islands (US)',]);
        DB::table('country')->insert(['cc_fips' => 'VT','cc_iso' => 'VA','cc_tld' => '.va','country_name' => 'Holy See (Vatican City)',]);
        DB::table('country')->insert(['cc_fips' => 'WA','cc_iso' => 'NA','cc_tld' => '.na','country_name' => 'Namibia',]);
        DB::table('country')->insert(['cc_fips' => 'WE','cc_iso' => '-','cc_tld' => '-','country_name' => 'West Bank',]);
        DB::table('country')->insert(['cc_fips' => 'WF','cc_iso' => 'WF','cc_tld' => '.wf','country_name' => 'Wallis and Futuna',]);
        DB::table('country')->insert(['cc_fips' => 'WI','cc_iso' => 'EH','cc_tld' => '.eh','country_name' => 'Western Sahara',]);
        DB::table('country')->insert(['cc_fips' => 'WQ','cc_iso' => 'UM','cc_tld' => '-','country_name' => 'Wake Island',]);
        DB::table('country')->insert(['cc_fips' => 'WS','cc_iso' => 'WS','cc_tld' => '.ws','country_name' => 'Samoa',]);
        DB::table('country')->insert(['cc_fips' => 'WZ','cc_iso' => 'SZ','cc_tld' => '.sz','country_name' => 'Swaziland',]);
        DB::table('country')->insert(['cc_fips' => 'YI','cc_iso' => 'CS','cc_tld' => '.yu','country_name' => 'Serbia and Montenegro',]);
        DB::table('country')->insert(['cc_fips' => 'YM','cc_iso' => 'YE','cc_tld' => '.ye','country_name' => 'Yemen',]);
        DB::table('country')->insert(['cc_fips' => 'ZA','cc_iso' => 'ZM','cc_tld' => '.zm','country_name' => 'Zambia',]);
        DB::table('country')->insert(['cc_fips' => 'ZI','cc_iso' => 'ZW','cc_tld' => '.zw','country_name' => 'Zimbabwe',]);
    }
}

